name: test-and-upload
on: [push, workflow_dispatch] 

jobs: 
  test-upload: 
    name: test and upload to codecov
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: set up go 
      uses: actions/setup-go@v2
      with: 
        go-version: '^1.15.6'
    - name: download dependencies 
      run: go mod download
    - name: run go tests 
      run: go test -coverprofile=coverage.txt -covermode=atomic
    - name: upload to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        verbose: true 
