name: test-and-upload
on: [push, workflow_dispatch] 

jobs: 
  test-upload: 
    name: test and upload to codecov
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: set up go 
      uses: actions/setup-go@v2
      with: 
        go-version: '^1.15.6'
    - name: setup gotestsum 
      uses: autero1/action-gotestsum@v0.1.0
      with: 
        gotestsum_version: '0.6.0'
    - name: run gotestsum 
      run: gotestsum --junitfile tests.xml
    - name: upload to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./tests.xml
        verbose: true 
